// Build script for the `vl` host. Two jobs, both about what the binary CARRIES.
//
// One is unconditional: stamp `$VL_BUILD_COMMIT` for `vl --version`. std is not
// staged here — `scripts/vl-host/src/std_embedded.rs` is checked in, generated by
// `deno task gen-std` from the same walk that writes the editor's map, so editing
// std needs no Rust toolchain and one test gates both copies.
//
// The other: when built with `--features embed-seed`, stage the compiler seed
// wasm into OUT_DIR so `include_bytes!(concat!(env!("OUT_DIR"), "/vl-compiler.wasm"))`
// in main.rs can bake it into the binary — giving a single self-contained `vl` for
// distribution. The seed path is `$VL_EMBED_SEED`, else the repo's default
// `build/vl-compiler.wasm` (relative to this crate). WITHOUT the feature this is a
// no-op, so a normal dev/CI build needs no seed present at compile time (ci-native
// builds the host before it mints the seed).

use std::path::PathBuf;

/// The commit this binary was built from, baked as `$VL_BUILD_COMMIT` for
/// `vl --version`. A pin is one file, so the file has to say which tree it is —
/// `unknown` outside a git checkout, which is honest and never fails the build.
/// Deliberately NOT `rerun-if-changed` on `.git/HEAD`: a stamp worth a rebuild on
/// every branch switch would cost more than it tells anyone.
fn stamp_commit() {
    let commit = std::process::Command::new("git")
        .args(["rev-parse", "--short=12", "HEAD"])
        .current_dir(std::env::var_os("CARGO_MANIFEST_DIR").unwrap())
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=VL_BUILD_COMMIT={commit}");
}

/// The host's identity for the compile cache, baked as `$VL_HOST_BUILD_ID`: an FNV-1a hash
/// of every host source, `build.rs`, the manifest, the lock file and the active feature set,
/// so a dirty local build differs from a clean one. The `rerun-if-changed` lines are printed
/// on every path, because once any is printed cargo re-runs this script only for the files
/// they name, and a stale id would serve one host's results to another.
fn stamp_host_build_id() {
    let dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir.join("src"))
        .map(|rd| rd.flatten().map(|e| e.path()).collect())
        .unwrap_or_default();
    files.sort();
    files.extend(["build.rs", "Cargo.toml", "Cargo.lock"].iter().map(|f| dir.join(f)));
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    let mut eat = |bytes: &[u8]| {
        for b in bytes.iter().chain((bytes.len() as u64).to_le_bytes().iter()) {
            h ^= *b as u64;
            h = h.wrapping_mul(0x0000_0100_0000_01b3);
        }
    };
    for f in &files {
        eat(f.file_name().unwrap_or_default().to_string_lossy().as_bytes());
        eat(&std::fs::read(f).unwrap_or_default());
    }
    let mut features: Vec<String> = std::env::vars()
        .map(|(k, _)| k)
        .filter(|k| k.starts_with("CARGO_FEATURE_"))
        .collect();
    features.sort();
    for f in &features {
        eat(f.as_bytes());
    }
    println!("cargo:rustc-env=VL_HOST_BUILD_ID={h:016x}");
    for f in ["src", "build.rs", "Cargo.toml", "Cargo.lock"] {
        println!("cargo:rerun-if-changed={f}");
    }
}

fn main() {
    stamp_commit();
    stamp_host_build_id();

    // Cargo sets CARGO_FEATURE_<NAME> for each active feature.
    if std::env::var_os("CARGO_FEATURE_EMBED_SEED").is_none() {
        return;
    }

    let seed = std::env::var_os("VL_EMBED_SEED")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            // CARGO_MANIFEST_DIR = scripts/vl-host; the seed lives at repo build/.
            PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap())
                .join("../../build/vl-compiler.wasm")
        });

    let out =
        PathBuf::from(std::env::var_os("OUT_DIR").unwrap()).join("vl-compiler.wasm");

    let bytes = std::fs::read(&seed).unwrap_or_else(|e| {
        panic!(
            "embed-seed: cannot read the compiler seed `{}`: {e}\n  \
             build it first (scripts/fetch-seed.sh or scripts/refresh-compiler.sh), \
             or point $VL_EMBED_SEED at a seed wasm.",
            seed.display(),
        )
    });
    std::fs::write(&out, &bytes).expect("embed-seed: staging the seed into OUT_DIR");

    // The embedded seed's identity, baked in as `$VL_SEED_KEY`, so the runtime can
    // name a compilation cache for bytes that have no path (see `seed_cache_path`).
    // Computed HERE rather than at startup because hashing a ~1 MB seed on every
    // invocation would cost a visible slice of the very latency the cache exists to
    // remove. FNV-1a: no dependency, and the key only has to be stable and
    // collision-free across seeds, not cryptographic.
    //
    // This is NOT why an `embed-seed` build recompiles when the seed changes — that is
    // the `rerun-if-changed` below, which cargo resolves by mtime, and which cannot go:
    // the seed is `include_bytes!`d, so a changed seed MUST rebuild. Moving this key to
    // run time was measured and changes nothing (perf-program.md §20).
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in &bytes {
        h ^= *b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    println!("cargo:rustc-env=VL_SEED_KEY={h:016x}");

    println!("cargo:rerun-if-changed={}", seed.display());
    println!("cargo:rerun-if-env-changed=VL_EMBED_SEED");
}
