// Generates `std/embedded.ts` — the checked-in module-key → source map of
// every `std/*.vl` (recursive) — for the consumers with no filesystem access
// to the repo `std/` dir: the LSP bundle (both checkers, via `withStd`) and
// the browser playground. The CLI and the Rust host read `std/` directly, so
// only the embedded consumers depend on this file being fresh; freshness is
// gated by `tests/std_embedded_test.ts` (the goldens pattern).
//
//   deno task gen-std
//
// Deterministic output: module names sorted, sources embedded verbatim via
// JSON.stringify, so the file is byte-stable for a given `std/` tree.

const STD_DIR = new URL("../std/", import.meta.url);
const OUT = new URL("embedded.ts", STD_DIR);

/** Every `.vl` under `std/` (recursive), as `[moduleName, source]` pairs —
 * `moduleName` is the `std:`-less, extension-less relative path (`a/b.vl` →
 * `a/b`), sorted for stable output. */
export const collectStdSources = async (): Promise<[string, string][]> => {
  const out: [string, string][] = [];
  const walk = async (dir: URL, prefix: string): Promise<void> => {
    for await (const entry of Deno.readDir(dir)) {
      if (entry.isDirectory) {
        await walk(new URL(`${entry.name}/`, dir), `${prefix}${entry.name}/`);
      } else if (entry.isFile && entry.name.endsWith(".vl")) {
        const name = prefix + entry.name.slice(0, -".vl".length);
        out.push([name, await Deno.readTextFile(new URL(entry.name, dir))]);
      }
    }
  };
  await walk(STD_DIR, "");
  out.sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0);
  return out;
};

/** Render the full `std/embedded.ts` text for the given `[name, source]`
 * pairs. Exported so the freshness test asserts the checked-in file equals
 * exactly what this generator would write today. */
export const renderEmbedded = (sources: [string, string][]): string => {
  const entries = sources
    .map(([name, src]) => `  ${JSON.stringify(`std:${name}`)}: ${JSON.stringify(src)},`)
    .join("\n");
  return `// GENERATED by \`deno task gen-std\` from \`std/*.vl\` — do not edit.
// Freshness is gated by tests/std_embedded_test.ts; regenerate after any
// std source change. See docs/std-design.md D3 for who consumes this map
// (the LSP checkers via \`withStd\`, the playground) and who does NOT (the
// CLI and the Rust host read the \`std/\` dir directly).

/** Module key (\`std:NAME\`) → that std module's source. */
export const STD_SOURCES: Record<string, string> = {
${entries}
};
`;
};

if (import.meta.main) {
  const text = renderEmbedded(await collectStdSources());
  await Deno.writeTextFile(OUT, text);
  console.error(`wrote ${OUT.pathname} (${text.length} bytes)`);
}
