// Generates the two CHECKED-IN copies of `std/*.vl`, from one walk of one tree:
//
//   std/embedded.ts               the LSP bundle's + playground's module map
//   scripts/vl-host/src/std_embedded.rs   the `vl` binary's baked-in std
//
// and, from the same walk, `compiler/std_receivers.vl`: std's receiver-style exports, which
// the checker's missing-import hint names without loading the module (D3122).
//
// ONE GENERATOR, because a release `vl` now ships std inside it (D1573) and the
// editor already did: two generators reading the same directory would still be
// two things to keep fresh, and the pair going out of step is invisible — the
// editor and the CLI would simply disagree about std. Both files are written by
// the same invocation and gated by the same test (tests/std_embedded_test.ts),
// so staleness is one failure, not two.
//
//   deno task gen-std
//
// Deterministic output: module names sorted, sources embedded verbatim, so both
// files are byte-stable for a given `std/` tree.
//
// `stdHash` is the identity `vl std --hash` and `vl --version` print. The Rust
// host recomputes it over its own copy (`std_hash` in main.rs), so the two
// implementations are cross-checked by tests/vl_std_cmd_test.ts rather than
// trusted.

const STD_DIR = new URL("../std/", import.meta.url);
const OUT = new URL("embedded.ts", STD_DIR);
const OUT_RS = new URL("../scripts/vl-host/src/std_embedded.rs", import.meta.url);

/** Every `.vl` under `std/` (recursive), as `[moduleName, source]` pairs —
 * `moduleName` is the `std:`-less, extension-less relative path (`a/b.vl` →
 * `a/b`), sorted for stable output. */
export const collectStdSources = async (): Promise<[string, string][]> => {
  const out: [string, string][] = [];
  const walk = async (dir: URL, prefix: string): Promise<void> => {
    for await (const entry of Deno.readDir(dir)) {
      if (entry.isDirectory) {
        await walk(new URL(`${entry.name}/`, dir), `${prefix}${entry.name}/`);
      } else if (entry.isFile && entry.name.endsWith(".vl")) {
        const name = prefix + entry.name.slice(0, -".vl".length);
        out.push([name, await Deno.readTextFile(new URL(entry.name, dir))]);
      }
    }
  };
  await walk(STD_DIR, "");
  out.sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0);
  return out;
};

/** The identity of a std TREE: FNV-1a 64 over `<name>\0<byte length>\0<source>\0`
 * per module, in sorted name order, as 16 hex digits. The length joins the fields
 * so no rename can forge another tree's digest. Not cryptographic — it answers
 * "is this the std that binary was built with", and a wrong answer costs a
 * confusing line in `vl --version`, never a wrong compile. */
export const stdHash = (sources: [string, string][]): string => {
  const MASK = (1n << 64n) - 1n;
  const PRIME = 0x100000001b3n;
  const enc = new TextEncoder();
  let h = 0xcbf29ce484222325n;
  const feed = (bytes: Uint8Array): void => {
    for (const b of bytes) h = ((h ^ BigInt(b)) * PRIME) & MASK;
  };
  for (const [name, src] of sources) {
    const body = enc.encode(src);
    feed(enc.encode(`${name}\0${body.length}\0`));
    feed(body);
    feed(new Uint8Array([0]));
  }
  return h.toString(16).padStart(16, "0");
};

/** Render the full `std/embedded.ts` text for the given `[name, source]`
 * pairs. Exported so the freshness test asserts the checked-in file equals
 * exactly what this generator would write today. */
export const renderEmbedded = (sources: [string, string][]): string => {
  const entries = sources
    .map(([name, src]) => `  ${JSON.stringify(`std:${name}`)}: ${JSON.stringify(src)},`)
    .join("\n");
  return `// GENERATED by \`deno task gen-std\` from \`std/*.vl\` — do not edit.
// Freshness is gated by tests/std_embedded_test.ts; regenerate after any
// std source change. See docs/std-design.md D3 for who consumes this map
// (the LSP checkers via \`withStd\`, the playground) and who does NOT (the
// CLI reads a std DIRECTORY when it has one — scripts/vl-host/src/std_embedded.rs
// is its own copy of this same tree, written by the same generator).

/** Module key (\`std:NAME\`) → that std module's source. */
export const STD_SOURCES: Record<string, string> = {
${entries}
};
`;
};

/** One VL source as a Rust string literal. Backslash and quote are escaped, the
 * three whitespace controls take their short forms, any other control byte takes
 * `\\u{..}`, and every other character rides through as UTF-8 — which a Rust
 * source file is. One module per line, matching `embedded.ts`, so a std diff has
 * the same shape in both generated files. */
const rustString = (s: string): string => {
  let out = '"';
  for (const ch of s) {
    const c = ch.codePointAt(0) as number;
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (c < 0x20 || c === 0x7f) out += `\\u{${c.toString(16)}}`;
    else out += ch;
  }
  return out + '"';
};

/** Render `scripts/vl-host/src/std_embedded.rs` — the `vl` binary's own copy of
 * `std/*.vl`, in the same sorted order and with the same `std:`-less names the
 * host's module reader is handed. */
export const renderEmbeddedRust = (sources: [string, string][]): string => {
  const entries = sources
    .map(([name, src]) => `    (${rustString(name)}, ${rustString(src)}),`)
    .join("\n");
  return `// GENERATED by \`deno task gen-std\` from \`std/*.vl\` — do not edit.
// Freshness is gated by tests/std_embedded_test.ts, which regenerates both this
// file and std/embedded.ts from the tree and demands byte equality. Regenerate
// after any std source change: \`deno task gen-std\`.
//
// WHY THE BINARY CARRIES std AT ALL: a pinned \`vl\` is one file, and a release
// binary that read \`std/\` off the filesystem paired a master seed with a stale
// checkout's sources without a word (D1573). Resolution order and the
// development overrides that outrank this copy live in main.rs (\`std_source\`).

/// Every \`std/*.vl\`, as \`(module name without the \`std:\` prefix, source)\`,
/// sorted by name — the order \`stdHash\` in scripts/gen-std.ts folds them in.
pub static STD_MODULES: &[(&str, &str)] = &[
${entries}
];
`;
};

/** One exported `self`-function of std, as the checker's missing-import hint reads it. */
export type StdReceiver = {
  name: string;
  spec: string;
  self: string;
  tparams: string[];
  min: number;
  max: number;
};

// The leaf type names a receiver spelling may use and still be nameable by a program
// that imports nothing from the module: the checker's `builtinTyNames` minus `void`,
// `never` and `v128`, none of which a value you call a method on can have.
const RECV_LEAVES = new Set(["i32", "i64", "f32", "f64", "boolean", "string", "null", "u8"]);

// Split `s` at the top-level occurrences of `sep` (a one-character separator), ignoring
// any inside brackets, braces, parens or angle brackets. `=>` does not close a `<`.
const splitTop = (s: string, sep: string): string[] => {
  const out: string[] = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (c === "(" || c === "[" || c === "{" || c === "<") depth++;
    else if (c === ")" || c === "]" || c === "}") depth--;
    else if (c === ">" && s[i - 1] !== "=") depth--;
    else if (c === sep && depth === 0) {
      out.push(s.slice(start, i).trim());
      start = i + 1;
    }
  }
  const last = s.slice(start).trim();
  if (last !== "") out.push(last);
  return out;
};

/** Whether a program that imports nothing from the declaring module can hold a value of
 * receiver spelling `self`: only builtin leaves, the function's own type parameters,
 * `[]`, a leading `readonly` and `|`. A nominal receiver (`Buf`, `Json`) can only come
 * from its module, which is then in the module graph and answered exactly there. */
export const receiverIsBuiltinSpelled = (self: string, tparams: string[]): boolean => {
  const body = self.startsWith("readonly ") ? self.slice("readonly ".length) : self;
  return splitTop(body, "|").every((m) => {
    let leaf = m;
    while (leaf.endsWith("[]")) leaf = leaf.slice(0, -2);
    return RECV_LEAVES.has(leaf) || tparams.includes(leaf);
  });
};

/** Every exported, `.name`-callable `self`-function in `sources` whose receiver is
 * builtin-spelled, then every RENAMING re-export of one under the re-exporting module's
 * key. A re-export under the same name is the same function, so the defining module is
 * its one answer and a fix can import from it without choosing. */
export const collectStdReceivers = (sources: [string, string][]): StdReceiver[] => {
  const defs: StdReceiver[] = [];
  const head = /^export function ([A-Za-z_][A-Za-z0-9_]*)\s*(<[^(]*>)?\s*\(/gm;
  for (const [name, src] of sources) {
    for (const m of src.matchAll(head)) {
      const open = (m.index as number) + m[0].length;
      let depth = 1;
      let i = open;
      while (depth > 0) {
        const c = src[i++];
        if (c === "(") depth++;
        else if (c === ")") depth--;
      }
      const params = splitTop(src.slice(open, i - 1).replace(/\s+/g, " "), ",");
      const selfMatch = /^self\s*:\s*(.+)$/.exec(params[0] ?? "");
      if (!selfMatch) continue;
      const tparams = m[2] ? splitTop(m[2].slice(1, -1), ",").map((t) => t.split(/[\s:]/)[0]) : [];
      const self = selfMatch[1].trim();
      if (!receiverIsBuiltinSpelled(self, tparams)) continue;
      const rest = params.slice(1);
      const variadic = rest.some((p) => p.startsWith("..."));
      const required = rest.filter((p) => !p.startsWith("...") && !/=(?!>)/.test(p)).length;
      defs.push({
        name: m[1],
        spec: `std:${name}`,
        self,
        tparams,
        min: required,
        max: variadic ? -1 : rest.length,
      });
    }
  }
  const reexports: StdReceiver[] = [];
  const reexp = /^export \{([^}]*)\} from "(std:[^"]+)"/gm;
  for (const [name, src] of sources) {
    for (const m of src.matchAll(reexp)) {
      for (const item of m[1].split(",").map((s) => s.trim()).filter((s) => s !== "")) {
        const [orig, alias] = item.split(/\s+as\s+/);
        for (const d of defs) {
          if (d.spec === m[2] && d.name === orig && alias !== undefined) {
            reexports.push({ ...d, name: alias ?? orig, spec: `std:${name}` });
          }
        }
      }
    }
  }
  return [...defs, ...reexports];
};

/** Every value std DECLARES for export (`export function|const|let`), as `[name, spec]`,
 * one row per pair. A re-export is left out: it names the same declaration, so the
 * declaring module is the one answer and two rows would make the name look ambiguous.
 * A `__`-prefixed name is internal to std and never offered. */
export const collectStdValueExports = (sources: [string, string][]): [string, string][] => {
  const out: [string, string][] = [];
  const head = /^export (?:function|const|let) ([A-Za-z_][A-Za-z0-9_]*)/gm;
  for (const [name, src] of sources) {
    const seen = new Set<string>();
    for (const m of src.matchAll(head)) {
      if (m[1].startsWith("__") || seen.has(m[1])) continue;
      seen.add(m[1]);
      out.push([m[1], `std:${name}`]);
    }
  }
  return out;
};

/** Render `compiler/std_receivers.vl`, the checker's copy of `collectStdReceivers`. */
export const renderStdReceivers = (sources: [string, string][]): string => {
  const rows = collectStdReceivers(sources)
    .map((r) =>
      `  stdRecvRow(${
        [r.name, r.spec, r.self, r.tparams.join(",")].map((s) => JSON.stringify(s)).join(", ")
      }, ${r.min}, ${r.max})`
    )
    .join("\n");
  const bySpec = new Map<string, string[]>();
  for (const [n, sp] of collectStdValueExports(sources)) {
    bySpec.set(sp, [...(bySpec.get(sp) ?? []), n]);
  }
  const exps = [...bySpec]
    .map(([sp, names]) => {
      const args = [JSON.stringify(sp), JSON.stringify(names.join(" "))];
      const one = `  stdExpRows(${args.join(", ")})`;
      // `vl fmt`'s own layout, so the generated file is already formatted: 80 columns.
      return one.length <= 80 ? one : `  stdExpRows(\n    ${args.join(",\n    ")},\n  )`;
    })
    .join("\n");
  return `// GENERATED by \`deno task gen-std\` from \`std/*.vl\` — do not edit; tests/std_embedded_test.ts
// gates freshness. One row per exported \`self\`-function of std whose receiver a program can
// hold without importing the module (builtin leaves, the function's type parameters, \`[]\`,
// \`readonly\`, \`|\`), then each renaming re-export of one. The missing-import hint (D1230, D3122)
// reads it for std modules the program's module graph does not contain.

// Per row: the name \`.name(…)\` spells, the specifier that imports it, the \`self\` annotation
// as written, the type parameter names \`,\`-joined, and the arguments after \`self\` — how many
// are required and how many accepted (-1: a rest parameter).
export let stdRecvName: string[] = []
export let stdRecvSpec: string[] = []
export let stdRecvSelf: string[] = []
export let stdRecvTparams: string[] = []
export let stdRecvMin: i32[] = []
export let stdRecvMax: i32[] = []

function stdRecvRow(
  name: string,
  spec: string,
  recv: string,
  tparams: string,
  min: i32,
  max: i32,
) {
  stdRecvName.push(name)
  stdRecvSpec.push(spec)
  stdRecvSelf.push(recv)
  stdRecvTparams.push(tparams)
  stdRecvMin.push(min)
  stdRecvMax.push(max)
}

// Fills the rows on first call; later calls are no-ops.
export function stdRecvLoad() {
  if stdRecvName.length > 0 { return }
${rows}
}

// Every value std declares for export, as name and specifier: what the undeclared-name
// hint offers to import. A re-export is left out, since it names the same declaration.
export let stdExpName: string[] = []
export let stdExpSpec: string[] = []

// One row per space-separated name in \`names\`, each exported by \`spec\`.
function stdExpRows(spec: string, names: string) {
  let start = 0
  let i = 0
  while i <= names.length {
    if i == names.length || names[i] == ' ' {
      stdExpName.push(names.slice(start, i))
      stdExpSpec.push(spec)
      start = i + 1
    }
    i = i + 1
  }
  0
}

// Fills the rows on first call; later calls are no-ops.
export function stdExpLoad() {
  if stdExpName.length > 0 { return }
${exps}
}
`;
};

const OUT_RECV = new URL("../compiler/std_receivers.vl", import.meta.url);

if (import.meta.main) {
  const sources = await collectStdSources();
  const text = renderEmbedded(sources);
  await Deno.writeTextFile(OUT, text);
  const rust = renderEmbeddedRust(sources);
  await Deno.writeTextFile(OUT_RS, rust);
  const recv = renderStdReceivers(sources);
  await Deno.writeTextFile(OUT_RECV, recv);
  console.error(`wrote ${OUT.pathname} (${text.length} bytes)`);
  console.error(`wrote ${OUT_RS.pathname} (${rust.length} bytes)`);
  console.error(`wrote ${OUT_RECV.pathname} (${recv.length} bytes)`);
  console.error(`std hash ${stdHash(sources)} over ${sources.length} modules`);
}
