"""Generates tests/cases/bitwise/shift-mask-fold.vl: every shape wasmEmit.vl's shift/mask strength
reduction rewrites (and its declining neighbours) at the boundary values, each @log computed here
by a bit-exact Python reference of the UNREDUCED expression.

    python3 scripts/gen-shift-mask-fold.py tests/cases/bitwise/shift-mask-fold.vl
"""
import sys

M32 = (1 << 32) - 1
M64 = (1 << 64) - 1


def s32(v):
    v &= M32
    return v - (1 << 32) if v >> 31 else v


def s64(v):
    v &= M64
    return v - (1 << 64) if v >> 63 else v


def shr_u(v, k, w):
    return (v & ((1 << w) - 1)) >> k


def shr_s(v, k, w):
    v &= (1 << w) - 1
    if v >> (w - 1):
        v -= 1 << w
    return v >> k


I32_IN = [("0", 0), ("-1", -1), ("IMIN", -(1 << 31)), ("IMAX", (1 << 31) - 1), ("0x12345678", 0x12345678)]
I64_IN = [("0", 0), ("-1", -1), ("LMIN", -(1 << 63)), ("LMAX", (1 << 63) - 1),
          ("LMIX", 0x9e3779b97f4a7c15 - (1 << 64)), ("LHALF", 0x80000000)]

funcs = []  # (name, param type, body, ref fn(x) -> value)


def add(name, ty, body, ref):
    funcs.append((name, ty, body, ref))


def mlit(m):
    return str(m) if m < 1024 else hex(m)


n = 0
# i32: ((x >>> k) & m) << j, and x >> k, and `* 2^j` on either side.
for op in [">>>", ">>"]:
    for k in [0, 3, 31]:
        for m in [0, 1023, 0x7FFFFFFF]:
            for j in [0, 3, 31]:
                sh = shr_u if op == ">>>" else shr_s
                ref = (lambda k, m, j, sh: lambda x: s32((sh(x, k, 32) & m) << j))(k, m, j, sh)
                n += 1
                add(f"a{n}", "i32", f"((x {op} {k}) & {mlit(m)}) << {j}", ref)
            for j in [3, 30]:
                sh = shr_u if op == ">>>" else shr_s
                ref = (lambda k, m, j, sh: lambda x: s32((sh(x, k, 32) & m) * (1 << j)))(k, m, j, sh)
                n += 1
                if j == 3:
                    add(f"a{n}", "i32", f"{1 << j} * ({mlit(m)} & (x {op} {k}))", ref)
                else:
                    add(f"a{n}", "i32", f"((x {op} {k}) & {mlit(m)}) * {1 << j}", ref)
# i32 through top-level consts.
add("c1", "i32", "((x >>> SH) & MASK) * SCALE", lambda x: s32((shr_u(x, 3, 32) & 1023) * 8))
add("c2", "i32", "((x >>> SH) & MASK) << SH", lambda x: s32((shr_u(x, 3, 32) & 1023) << 3))
# i64: the same at width 64.
for op in [">>>", ">>"]:
    for k in [0, 3, 63]:
        for m in [1023, 0xFFFFFFFF]:
            for j in [0, 3, 63]:
                sh = shr_u if op == ">>>" else shr_s
                ref = (lambda k, m, j, sh: lambda x: s64((sh(x, k, 64) & m) << j))(k, m, j, sh)
                n += 1
                add(f"b{n}", "i64", f"((x {op} {k}) & {mlit(m)}) << {j}", ref)
            sh = shr_u if op == ">>>" else shr_s
            ref = (lambda k, m, sh: lambda x: s64((sh(x, k, 64) & m) * 8))(k, m, sh)
            n += 1
            add(f"b{n}", "i64", f"((x {op} {k}) & {mlit(m)}) * 8", ref)
# i64 -> i32 narrowing: (y >>> k) as% i32 & m, with and without a following << j / * 2^j,
# and ((y >>> k) & m) as% i32, with and without.
for op in [">>>", ">>"]:
    for k in [0, 3, 31, 32]:
        for m in [1, 1023, 0x7FFFFFFF]:
            sh = shr_u if op == ">>>" else shr_s
            ref = (lambda k, m, sh: lambda y: s32(sh(y, k, 64) & M32 & m))(k, m, sh)
            n += 1
            add(f"n{n}", "i64", f"(y {op} {k}) as% i32 & {mlit(m)}", ref)
            for j in [3, 31]:
                ref = (lambda k, m, j, sh: lambda y: s32(((sh(y, k, 64) & M32) & m) << j))(k, m, j, sh)
                n += 1
                add(f"n{n}", "i64", f"((y {op} {k}) as% i32 & {mlit(m)}) << {j}", ref)
            ref = (lambda k, m, sh: lambda y: s32(((sh(y, k, 64) & M32) & m) * 8))(k, m, sh)
            n += 1
            add(f"n{n}", "i64", f"((y {op} {k}) as% i32 & {mlit(m)}) * 8", ref)
        for m in [1023, 0xFFFFFFFF]:
            ref = (lambda k, m, sh: lambda y: s32(sh(y, k, 64) & m))(k, m, sh)
            n += 1
            add(f"w{n}", "i64", f"((y {op} {k}) & {mlit(m)}) as% i32", ref)
            ref = (lambda k, m, sh: lambda y: s32((sh(y, k, 64) & m) << 3))(k, m, sh)
            n += 1
            add(f"w{n}", "i64", f"((y {op} {k}) & {mlit(m)}) as% i32 << 3", ref)

out = []
out.append("// @run")
logs = []
body = []
body.append("// Every shape the emitter's shift/mask strength reduction rewrites, at the boundary")
body.append("// values: `((x >>> k) & m) << j` and `* 2^j` at i32 and i64, `>>` where the mask misses")
body.append("// the sign fill, and the i64 -> i32 narrowings. Shifts at 0, 31 and 63, masks at 0 and")
body.append("// all-ones; the declining neighbours are here too, so both sides print the same values.")
body.append("// Each line is one shape's results over the inputs, folded by `mix`. Generated by")
body.append("// scripts/gen-shift-mask-fold.py; see wasmEmit.vl `emitShiftMaskFold`.")
body.append("const SH = 3")
body.append("const MASK = 1023")
body.append("const SCALE = 8")
body.append("const IMIN = 1 << 31")
body.append("const IMAX = IMIN - 1")
body.append("const LMIN: i64 = (1 as i64) << 63")
body.append("const LMAX: i64 = LMIN - 1")
body.append("const LMIX: i64 = 0x9e3779b97f4a7c15")
body.append("const LHALF: i64 = 0x80000000")
body.append("function mix(h: i64, v: i64) { h * 1000003 + v }")
for name, ty, expr, ref in funcs:
    p = "y" if name[0] in "nw" else "x"
    body.append(f"function {name}({p}: {ty}) {{ {expr} }}")
for name, ty, expr, ref in funcs:
    ins = I32_IN if ty == "i32" else I64_IN
    call = "0 as i64"
    h = 0
    for lit, v in ins:
        arg = lit
        if ty == "i64" and lit in ("0", "-1"):
            arg = f"{lit} as i64"
        call = f"mix({call}, {name}({arg}) as i64)"
        h = s64(h * 1000003 + ref(v))
    body.append(f"print({call})")
    logs.append(h)
for v in logs:
    out.append(f"// @log {v}")
out.extend(body)
open(sys.argv[1], "w").write("\n".join(out) + "\n")
print(len(funcs), "functions,", len(logs), "values", file=sys.stderr)
