#!/usr/bin/env python3
"""Generate tests/cases/atomics/{load-store,rmw,cmpxchg}.vl: every atomic intrinsic against
known memory, with the expected `@log` lines from an independent model of the wasm threads
proposal's semantics (an access is little-endian; a narrow load or rmw zero-extends the old
value; a narrow operand, replacement and cmpxchg `expected` are wrapped to the access width).

The corpus oracle runs the cases on V8; `vl run` runs them on wasmtime. Re-run after changing
the atomic table:

    python3 scripts/gen-atomic-cases.py            # write the cases
    python3 scripts/gen-atomic-cases.py --verify   # also check every opcode against wasm-dis
"""
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
OUT = os.path.join(ROOT, "tests", "cases", "atomics")

# ── the spec table: wasm name, 0xFE sub-opcode, VL name ─────────────────────
# Written from the threads proposal's opcode list, not read from the compiler, so `--verify`
# compares two independent sources (and binaryen's decoder as the third).

WIDTHS = [("i32", 32, ""), ("i64", 64, ""), ("i32", 8, "8"), ("i32", 16, "16"),
          ("i64", 8, "8"), ("i64", 16, "16"), ("i64", 32, "32")]
RMW_OPS = ["add", "sub", "and", "or", "xor", "xchg", "cmpxchg"]


def spec_table():
    rows = [("memory.atomic.notify", 0x00, "__atomic_notify__"),
            ("memory.atomic.wait32", 0x01, "__atomic_wait32__"),
            ("memory.atomic.wait64", 0x02, "__atomic_wait64__"),
            ("atomic.fence", 0x03, "__atomic_fence__")]
    for i, (shape, _, n) in enumerate(WIDTHS):
        u = "_u" if n else ""
        rows.append((f"{shape}.atomic.load{n}{u}", 0x10 + i, f"__atomic_load{n}{u}_{shape}__"))
    for i, (shape, _, n) in enumerate(WIDTHS):
        rows.append((f"{shape}.atomic.store{n}", 0x17 + i, f"__atomic_store{n}_{shape}__"))
    for k, op in enumerate(RMW_OPS):
        for i, (shape, _, n) in enumerate(WIDTHS):
            u = "_u" if n else ""
            rows.append((f"{shape}.atomic.rmw{n}.{op}{u}", 0x1e + 7 * k + i,
                         f"__atomic_rmw{n}_{op}{u}_{shape}__"))
    return rows


# ── the reference model ─────────────────────────────────────────────────────

BASE = 256  # a 16-byte window, 8-aligned; every access lands inside it
SEED = bytes([0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88,
              0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xF0, 0xFF])
OFFSET = {8: 5, 16: 6, 32: 4, 64: 8}  # naturally aligned, and not at the window's start


def signed(v, bits):
    v %= 1 << bits
    return v - (1 << bits) if v >= 1 << (bits - 1) else v


def get(mem, off, bits):
    return int.from_bytes(mem[off:off + bits // 8], "little")


def put(mem, off, bits, v):
    mem[off:off + bits // 8] = (v % (1 << bits)).to_bytes(bits // 8, "little")


def lit(v, shape):
    """A VL literal of `v` (already signed at the shape's width)."""
    if shape == "i32":
        return "(-2147483647 - 1)" if v == -(1 << 31) else str(v)
    return "(-9223372036854775807 - 1)" if v == -(1 << 63) else str(v)


RMW = {
    "add": lambda a, b: a + b,
    "sub": lambda a, b: a - b,
    "and": lambda a, b: a & b,
    "or": lambda a, b: a | b,
    "xor": lambda a, b: a ^ b,
    "xchg": lambda a, b: b,
}

OPERANDS = {  # signed at the row's shape; narrow rows see only their low bits
    "i32": [1, -1, 0x7FFFFFFF, -(1 << 31), 0x1F0F, -0x1234568],
    "i64": [1, -1, (1 << 63) - 1, -(1 << 63), 0x1F0F, -0x123456789ABC],
}


class Case:
    def __init__(self, name, blurb):
        self.name, self.blurb = name, blurb
        self.body, self.logs = [], []

    def reset(self):
        self.body.append("  seed()")
        return bytearray(SEED)

    def value(self, expr, v, shape):
        self.body.append(f"  print({expr})")
        self.logs.append(str(signed(v, 32 if shape == "i32" else 64)))

    def window(self, mem):
        self.body.append("  window()")
        self.logs += [str(signed(get(mem, 0, 64), 64)), str(signed(get(mem, 8, 64), 64))]

    def write(self):
        text = ["// @run"] + [f"// @log {l}" for l in self.logs]
        text += [f"// {line}" for line in self.blurb]
        text += ["// Generated by scripts/gen-atomic-cases.py; the expected lines are its model of",
                 "// the wasm threads proposal. Edit the generator, not this file.",
                 f"const BASE = {BASE}",
                 "",
                 "function seed() {",
                 f"  __store_i64__(BASE, {signed(get(SEED, 0, 64), 64)})",
                 f"  __store_i64__(BASE + 8, {signed(get(SEED, 8, 64), 64)})",
                 "}",
                 "",
                 "function window() {",
                 "  print(__load_i64__(BASE))",
                 "  print(__load_i64__(BASE + 8))",
                 "}",
                 "",
                 "function main() {"] + self.body + ["}", "main()", ""]
        with open(os.path.join(OUT, self.name), "w") as fh:
            fh.write("\n".join(text))


def gen_load_store():
    c = Case("load-store.vl", [
        "Every atomic load and store width at a naturally aligned address inside a seeded",
        "16-byte window: a narrow load zero-extends, and a narrow store writes only its",
        "own bytes, so the window's other bytes read back unchanged.",
    ])
    for shape, bits, n in WIDTHS:
        u = "_u" if n else ""
        mem = c.reset()
        for off in sorted({0, OFFSET[bits], 16 - bits // 8}):
            c.value(f"__atomic_load{n}{u}_{shape}__(BASE + {off})", get(mem, off, bits), shape)
    for shape, bits, n in WIDTHS:
        for v in OPERANDS[shape][1:4]:
            mem = c.reset()
            off = OFFSET[bits]
            c.body.append(f"  __atomic_store{n}_{shape}__(BASE + {off}, {lit(v, shape)})")
            put(mem, off, bits, v)
            c.window(mem)
    c.write()


def gen_rmw():
    c = Case("rmw.vl", [
        "Every read-modify-write op at every width: the call answers the OLD value",
        "(zero-extended when narrow) and memory holds op(old, operand) wrapped to the",
        "width, with the window's other bytes unchanged. Operands carry bits above a",
        "narrow width, which the access wraps away.",
    ])
    for op, f in RMW.items():
        for shape, bits, n in WIDTHS:
            u = "_u" if n else ""
            for v in OPERANDS[shape][::2] if op != "add" else OPERANDS[shape]:
                mem = c.reset()
                off = OFFSET[bits]
                old = get(mem, off, bits)
                c.value(f"__atomic_rmw{n}_{op}{u}_{shape}__(BASE + {off}, {lit(v, shape)})",
                        old, shape)
                put(mem, off, bits, f(old, v % (1 << bits)))
                c.window(mem)
    # an operand read at run time, not folded from a literal
    mem = c.reset()
    c.body.append("  let k = 3")
    c.body.append("  k = k * 7")
    c.value("__atomic_rmw_sub_i32__(BASE + 4, k)", get(mem, 4, 32), "i32")
    put(mem, 4, 32, get(mem, 4, 32) - 21)
    c.window(mem)
    c.write()


REPL = -0x5A5A5A5A5A5A5A5B  # the replacement, read from a binding at its row's width


def gen_cmpxchg():
    c = Case("cmpxchg.vl", [
        "cmpxchg at every width, on a match and on a mismatch. Each answers the OLD value;",
        "only a match stores the replacement. A narrow `expected` is wrapped to the access",
        "width before the compare, so one whose high bits are set still matches.",
    ])
    c.body.append(f"  const r32 = {signed(REPL, 32)}")
    c.body.append(f"  const r64 = {signed(REPL, 64)}")
    for shape, bits, n in WIDTHS:
        u = "_u" if n else ""
        name = f"__atomic_rmw{n}_cmpxchg{u}_{shape}__"
        off = OFFSET[bits]
        top = 32 if shape == "i32" else 64
        repl = signed(REPL, top)
        cur = get(SEED, off, bits)
        cases = [signed(cur, top), signed(cur + 1, top)]  # match, then mismatch
        if n:
            cases.append(signed(cur | (1 << bits) | (1 << (top - 1)), top))  # wraps to a match
        for exp in cases:
            mem = c.reset()
            c.value(f"{name}(BASE + {off}, {lit(exp, shape)}, r{top})", cur, shape)
            if exp % (1 << bits) == cur:
                put(mem, off, bits, repl)
            c.window(mem)
    c.write()


def check_coverage():
    text = "".join(open(os.path.join(OUT, f)).read() for f in os.listdir(OUT))
    missing = [vl for _, _, vl in spec_table() if vl + "(" not in text]
    if missing:
        raise SystemExit("rows with no generated case: " + ", ".join(missing))


def leb(data, i):
    v = shift = 0
    while True:
        b = data[i]
        v |= (b & 0x7F) << shift
        i += 1
        shift += 7
        if b < 0x80:
            return v, i


def code_section(data):
    i = 8
    while i < len(data):
        sid = data[i]
        size, j = leb(data, i + 1)
        if sid == 10:
            return data[j:j + size]
        i = j + size
    raise SystemExit("no code section")


def verify():
    """Builds one module calling every intrinsic in spec order and checks (1) its 0xFE
    sub-opcodes against the spec table, byte for byte, and (2) binaryen's disassembly names."""
    rows = spec_table()
    lines = []
    for wasm, _, vl in rows:
        args = {"notify": "16, 1", "wait32": "16, 1, 0 as i64", "wait64": "16, 1 as i64, 0 as i64",
                "fence": ""}
        key = vl.strip("_").split("_")[1]
        if key in args:
            a = args[key]
        elif ".cmpxchg" in wasm:
            a = "16, 1, 2"
        elif ".load" in wasm:
            a = "16"
        else:
            a = "16, 1"
        call = f"{vl}({a})"
        lines.append(call if wasm.startswith("atomic.fence") or ".store" in wasm else f"print({call})")
    with tempfile.TemporaryDirectory() as d:
        src, wasm_path = os.path.join(d, "all.vl"), os.path.join(d, "all.wasm")
        open(src, "w").write("\n".join(lines) + "\n")
        vl = os.environ.get("VL", os.path.join(ROOT, "scripts/vl-host/target/release/vl"))
        seed = os.path.join(ROOT, "build/vl-compiler.wasm")
        subprocess.run([vl, "build", src, "--compiler", seed, "-o", wasm_path], check=True,
                       stdout=subprocess.DEVNULL)
        data = open(wasm_path, "rb").read()
        dis = subprocess.run([os.path.join(ROOT, "node_modules/.bin/wasm-dis"), wasm_path,
                              "--enable-threads", "--enable-gc", "--enable-reference-types"],
                             check=True, capture_output=True, text=True).stdout
    # Every sub-opcode is < 0x80, so each call site is the two bytes `0xFE <sub>`. The main
    # function's body is straight-line calls on small constants, so in the CODE section no
    # other 0xFE byte occurs; the sequence must equal the spec table's exactly.
    code = code_section(data)
    ops = [code[i + 1] for i in range(len(code) - 1) if code[i] == 0xFE]
    want = [op for _, op, _ in rows]
    names = re.findall(r"\((memory\.atomic\.\w+|atomic\.fence|i(?:32|64)\.atomic\.[\w.]+)", dis)
    bad = [(w, n) for (w, _, _), n in zip(rows, names) if w != n]
    print(f"opcodes: {len(ops)} emitted, {'equal to' if ops == want else 'DIFFERENT from'} the "
          f"spec table's {len(want)}; wasm-dis: {len(names)} decoded, {len(bad)} disagree")
    if ops != want or len(names) != len(rows) or bad:
        raise SystemExit(f"verify failed: {bad[:5]}")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    gen_load_store()
    gen_rmw()
    gen_cmpxchg()
    check_coverage()
    if "--verify" in sys.argv:
        verify()
