#!/usr/bin/env python3
"""
Row parsing shared by the inventory split tools.

THE ROW GRAMMAR LIVES IN `scripts/check-filed-witnesses.py` and is imported from there
rather than re-spelled: two copies of `SEC` would drift, and the drift is silent in the
direction that matters — a heading the grader parses and the splitter does not is a row
that ends up inside another row's file.

ONE DIFFERENCE, DELIBERATE. The grader ends a row's scope at ANY heading, because it only
needs the status line and the first repro block, both of which precede a row's `####`
subsections. A SPLIT cannot do that: ending at `#### The close` would truncate the row. So
a row here runs to the next row heading or the next `#`/`##` SECTION heading, and
`inner_section_heads` asserts no `###` heading hides inside a row extent (0 in both
inventories, re-checked on every run).
"""
import importlib.util
import re
from pathlib import Path

CHECKER = Path(__file__).resolve().parents[1] / "check-filed-witnesses.py"


def checker():
    """`scripts/check-filed-witnesses.py` as a module — its name has hyphens in it."""
    spec = importlib.util.spec_from_file_location("filed_witnesses", CHECKER)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_CK = checker()
SEC = _CK.SEC                       # `### D1042 — title`, the grader's own pattern
ROWHEAD = _CK.ROWHEAD               # a heading that plainly NAMES a row, whatever suffix
declared_outcome = _CK.declared_outcome
id_key = _CK.row_id_key             # `D9` before `D10`, `D661` before `D661A`
resolve = _CK.resolve               # a monolith path, or a directory of one-row files
unparsed_row_heads = _CK.unparsed_row_heads   # row-shaped headings `SEC` cannot parse
SECTION = re.compile(r"^#{1,2}\s")  # `#` / `##` — the only headings that end a row

# The pointer a split directory keeps back to the monolith it came from, so a consumer
# handed an EMPTY directory (the state this PR ships) reads the monolith instead of
# reporting zero rows. One source of truth, read by python and by the deno test.
SOURCE_MARK = re.compile(r"^<!--\s*inventory-split:\s*source\s+(\S+)\s*-->\s*$", re.M)
PROSE_MARK = ("<!-- inventory-split: relocated prose follows; "
              "regenerated by scripts/inventory/split.py --apply -->")


class Block:
    """A row (`kind == "row"`) or the prose between rows, with its source line."""

    def __init__(self, kind, text, start, rid=None, title=None):
        self.kind, self.text, self.start = kind, text, start
        self.rid, self.title = rid, title

    @property
    def name(self):
        return self.rid if self.kind == "row" else f"prose at line {self.start}"


def parse_blocks(text):
    """The document as ordered Blocks. Concatenating `.text` with newlines rebuilds it."""
    lines = text.split("\n")
    blocks = []
    cur, kind, start, rid, title = [], "prose", 1, None, None
    for i, ln in enumerate(lines):
        m = SEC.match(ln)
        if m or (kind == "row" and SECTION.match(ln)):
            blocks.append(Block(kind, "\n".join(cur), start, rid, title))
            cur, start = [ln], i + 1
            if m:
                kind, rid, title = "row", m.group(1), m.group(2).strip()
            else:
                kind, rid, title = "prose", None, None
            continue
        cur.append(ln)
    blocks.append(Block(kind, "\n".join(cur), start, rid, title))
    return [b for b in blocks if b.kind == "row" or b.text != ""]


def inner_section_heads(text):
    """`###` headings caught INSIDE a row extent — none exist today, and none may."""
    out, inrow = [], False
    for i, ln in enumerate(text.split("\n")):
        if SEC.match(ln):
            inrow = True
        elif SECTION.match(ln):
            inrow = False
        elif inrow and re.match(r"^###\s", ln):
            out.append((i + 1, ln.strip()))
    return out


def strip_separator(text):
    r"""A row's text without the `---` rule that JOINS it to the next row.

    The rule and the blank lines around it belong to the monolith, not to the row: the
    monolith spells them four ways (287 rows `\n\n---\n`, 51 with no trailing blank, 12
    with no leading one, 7 with two) and six rows carry no rule at all. Dropping it is
    the ONLY edit the split makes — that is what `--verify`'s "modulo the separators"
    means — and everything left is proved a verbatim substring of the source.
    """
    lines = text.split("\n")
    j = len(lines)
    while j > 0 and not lines[j - 1].strip():
        j -= 1
    if j > 0 and lines[j - 1].strip() == "---":
        j -= 1
        while j > 0 and not lines[j - 1].strip():
            j -= 1
    return "\n".join(lines[:j]).rstrip("\n") + "\n"


def row_files(directory):
    """`D*.md` under `directory`, in id order. Empty until the split lands."""
    d = Path(directory)
    if not d.is_dir():
        return []
    return sorted(d.glob("D*.md"), key=lambda p: id_key(p.stem))
