#!/usr/bin/env python3
"""
Split a monolithic defect inventory into ONE FILE PER ROW, and prove nothing was lost.

WHY. `docs/internals/silent-class-inventory.md` is one ~38,000-line file that every defect
PR appends to, so two concurrent PRs conflict in its tail nearly every hour. On 2026-09-02
one such resolution spliced two rows into the middle of a third and reddened the gate twice.
One file per row removes the shared tail: two PRs filing two rows touch two files.

THE SPLIT LANDS BY RUNNING THIS, NOT BY A HAND-MAINTAINED DIFF. A 38,000-line diff rebases
wrongly and does it silently — the failure this exists to stop. A script re-runs against
merge-day master and produces the same answer, so `--apply` is idempotent and refuses to
write unless the losslessness checks pass first.

USAGE
    scripts/inventory/split.py                  # dry run: what would happen
    scripts/inventory/split.py --verify         # the losslessness checks, no writes
    scripts/inventory/split.py --apply          # write the split (verifies first)
    scripts/inventory/split.py --relink         # rewrite `...inventory.md#d123` links
    scripts/inventory/split.py --only 2         # restrict to inventory #2

WHAT `--verify` PROVES, in five checks that fail NAMING THE ROW:
  0. coverage — the parsed blocks re-concatenate to the source BYTE FOR BYTE, so no line
                can fall between two blocks however the heading grammar changes.
  1. ids      — every row heading parses, and no two rows claim one id.
  2. bytes    — each row file's text is a VERBATIM substring of the monolith.
  3. suffix   — each row file is a PREFIX of its source block, and the only thing dropped
                after it is blank lines and a lone `---` rule. This is what catches a
                TRUNCATED row, which check 2 cannot: a truncation is still a substring.
  4. rejoin   — the row files re-concatenated in ID ORDER equal the monolith's rows in id
                order, modulo those separators. Any difference prints as a unified diff.

Checks 2, 3 and 4 are strongest in their FROM-DISK form, where `stored` is what was
actually written rather than what was planned; that is the form `--apply` runs, after
writing and before the monolith is replaced. `scripts/inventory/selftest.py` makes each
one fire on a specimen whose fault is known by construction.
"""
import difflib
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rows as R  # noqa: E402

# (monolith, split directory). TWO namespaces, not one: inventory #2 numbers its rows
# independently and D1..D14 exist in BOTH files, so one flat directory cannot hold them
# — the first `--apply` would silently overwrite fourteen rows with fourteen others.
# `tests/vl_inventory_rows_test.ts` already checks id uniqueness PER DOCUMENT for the
# same reason. Adding a third inventory means adding a line here and nothing else.
SOURCES = [
    ("docs/internals/silent-class-inventory.md", "docs/internals/inventory"),
    ("docs/internals/silent-class-inventory-2.md", "docs/internals/inventory-2"),
]

SEP = "\n\n---\n\n"

POINTER = """# {title} — SPLIT, one file per row

**This file is a pointer.** Its {n} rows now live one per file under
[`{dirname}/`](./{dirname}/), because every defect PR appended to this file's tail and two
concurrent PRs conflicted there nearly every hour.

* one row, by id — `{dir}/D1042.md`
* the whole list — [`{dirname}/INDEX.md`](./{dirname}/INDEX.md)
* which rows are non-running — `python3 scripts/inventory/ls.py --status open`
* filing a new row — [`{dirname}/TEMPLATE.md`](./{dirname}/TEMPLATE.md)
* the prose that used to sit around the rows — [`{dirname}/README.md`](./{dirname}/README.md)

The path is KEPT rather than deleted so the ~60 citations that name it, and any link from
outside this repo, still resolve. Regenerated by `scripts/inventory/split.py --apply`.
"""

INDEX_HEAD = """<!-- GENERATED by scripts/inventory/split.py --apply — do not edit by hand. -->
# {title} — index ({n} rows)

`status` is the canonical outcome `scripts/check-filed-witnesses.py` reads out of the row's
own status line, not free text. `python3 scripts/inventory/ls.py --status open` is the same
list filtered to the rows that do not run.

| row | status | title |
| --- | --- | --- |
"""


def die(msg):
    print(f"split.py: {msg}", file=sys.stderr)
    return 1


class Plan:
    """One inventory's split: the row files, the prose, and the checks over them."""

    def __init__(self, src, dstdir):
        self.src, self.dir = Path(src), Path(dstdir)
        self.text = self.src.read_text() if self.src.exists() else ""
        self.blocks = R.parse_blocks(self.text)
        self.rowblocks = [b for b in self.blocks if b.kind == "row"]
        self.files = {b.rid: R.strip_separator(b.text) for b in self.rowblocks}
        head = self.text.split("\n", 1)[0].lstrip("# ").strip()
        # The `#` line's subtitle after the first em dash is prose, not a name.
        self.title = head.split(" — ")[0] or self.src.stem

    @property
    def applied(self):
        return bool(R.row_files(self.dir))

    def prose(self):
        """The non-row blocks, in document order, joined by the canonical rule."""
        parts = [b.text.strip("\n") for b in self.blocks if b.kind == "prose"]
        return SEP.join(p for p in parts if p.strip()) + "\n"

    def index(self):
        out = [INDEX_HEAD.format(title=self.title, n=len(self.rowblocks))]
        for b in sorted(self.rowblocks, key=lambda b: R.id_key(b.rid)):
            st = R.declared_outcome(status_line(self.files[b.rid]) or "") or "?"
            title = b.title.replace("|", "\\|")
            out.append(f"| [{b.rid}]({b.rid}.md) | {st} | {title} |\n")
        return "".join(out)

    # ---- the five checks --------------------------------------------------------------
    def check(self, from_disk):
        """Faults as `(row, why)` pairs; empty means lossless. `from_disk` reads the
        WRITTEN files rather than the plan, which is the strong form and the one
        `--apply` runs after writing and before the monolith is replaced."""
        faults = []
        faults += self._coverage()
        faults += self._ids()
        stored = self._stored(from_disk, faults)
        faults += self._bytes(stored)
        faults += self._suffix(stored)
        faults += self._rejoin(stored)
        return faults

    def _coverage(self):
        rebuilt = "\n".join(b.text for b in self.blocks)
        if rebuilt == self.text:
            return []
        i = next((k for k in range(min(len(rebuilt), len(self.text)))
                  if rebuilt[k] != self.text[k]), min(len(rebuilt), len(self.text)))
        return [("-", f"parsed blocks do NOT re-concatenate to {self.src}; "
                      f"first divergence at char {i}: {self.text[i:i + 60]!r}")]

    def _ids(self):
        faults, seen = [], {}
        for ln, head in R.unparsed_row_heads(str(self.src)):
            faults.append(("-", f"row heading at {self.src}:{ln} does not parse: {head}"))
        for b in self.rowblocks:
            if b.rid in seen:
                faults.append((b.rid, f"DUPLICATE id — also at line {seen[b.rid]}"))
            seen[b.rid] = b.start
        for h in R.inner_section_heads(self.text):
            faults.append(("-", f"`###` heading inside a row extent at line {h[0]}: {h[1]}"))
        return faults

    def _stored(self, from_disk, faults):
        if not from_disk:
            return dict(self.files)
        got = {}
        for p in R.row_files(self.dir):
            got[p.stem] = p.read_text()
        for rid in self.files:
            if rid not in got:
                faults.append((rid, f"planned but not written to {self.dir}/{rid}.md"))
        for rid in got:
            if rid not in self.files:
                faults.append((rid, f"{self.dir}/{rid}.md claims an id no source row has"))
        return got

    def _bytes(self, stored):
        """Every stored row must appear in the monolith verbatim — the byte-level claim."""
        faults = []
        for rid, body in stored.items():
            if rid in self.files and body.rstrip("\n") not in self.text:
                faults.append((rid, "row text is NOT a verbatim substring of the source"))
        return faults

    def _suffix(self, stored):
        """A row file must be a PREFIX of its source block, and the only bytes after it
        blank lines and a lone `---`. Computed against `stored`, so a file truncated at
        the wrong line fails here — check 2 cannot see that, a prefix being a substring."""
        faults = []
        for b in self.rowblocks:
            body = stored.get(b.rid)
            if body is None:
                continue
            keep = body.rstrip("\n")
            if not b.text.startswith(keep):
                faults.append((b.rid, "row file is not a prefix of its source block"))
                continue
            for ln in b.text[len(keep):].split("\n"):
                if ln.strip() not in ("", "---"):
                    faults.append((b.rid, f"dropped after the row: {ln.strip()[:60]!r}"))
        return faults

    def _rejoin(self, stored):
        want = SEP.join(R.strip_separator(b.text).rstrip("\n")
                        for b in sorted(self.rowblocks, key=lambda b: R.id_key(b.rid)))
        got = SEP.join(stored[r].rstrip("\n")
                       for r in sorted(stored, key=R.id_key) if r in self.files)
        if want == got:
            return []
        d = list(difflib.unified_diff(want.split("\n"), got.split("\n"),
                                      "monolith rows (id order)", "row files (id order)",
                                      lineterm="", n=1))
        return [("-", "rejoin differs:\n      " + "\n      ".join(d[:40]))]


def status_line(body):
    """The row's first `**bold**` line — the grader's own rule, wrap included."""
    lines = body.split("\n")
    for i, ln in enumerate(lines):
        if not ln.startswith("**"):
            continue
        if ln.rstrip().endswith("**") and len(ln.rstrip()) > 2:
            return ln.strip("*").strip()
        parts = [ln]
        for k in range(i + 1, min(i + 6, len(lines))):
            parts.append(lines[k])
            if lines[k].rstrip().endswith("**"):
                return " ".join(parts).strip("*").strip()
            if not lines[k].strip():
                break
        return None
    return None


def readme(plan):
    """Keep the hand-written filing note; regenerate everything after the prose marker."""
    path = plan.dir / "README.md"
    head = path.read_text().split(R.PROSE_MARK)[0].rstrip("\n") if path.exists() else ""
    if not head:
        head = (f"<!-- inventory-split: source {plan.src} -->\n\n"
                f"# {plan.title}\n")
    return f"{head}\n\n{R.PROSE_MARK}\n\n{plan.prose()}"


def do_apply(plan):
    """Write the directory, RE-VERIFY FROM DISK, and only then replace the monolith.

    The order is the point: if the written files disagree with the source by one byte, the
    source is still there and the run aborts naming the row. Verifying the plan and then
    trusting the write is the weaker check, and it is the one that would miss an encoding
    or line-ending fault introduced by the write itself."""
    if not plan.rowblocks:
        print(f"  {plan.src}: no rows — already split, regenerating INDEX only")
        if plan.applied:
            (plan.dir / "INDEX.md").write_text(index_of_disk(plan))
        return 0
    plan.dir.mkdir(parents=True, exist_ok=True)
    for rid, body in plan.files.items():
        (plan.dir / f"{rid}.md").write_text(body)
    stale = [p for p in R.row_files(plan.dir) if p.stem not in plan.files]
    for p in stale:
        p.unlink()
    faults = plan.check(from_disk=True)
    if faults:
        return report(plan, faults)
    (plan.dir / "INDEX.md").write_text(plan.index())
    (plan.dir / "README.md").write_text(readme(plan))
    plan.src.write_text(POINTER.format(title=plan.title, n=len(plan.rowblocks),
                                       dir=plan.dir, dirname=plan.dir.name))
    print(f"  {plan.src} -> {plan.dir}/  {len(plan.files)} rows, "
          f"{len(stale)} stale removed, prose -> README.md, source -> pointer")
    return 0


def index_of_disk(plan):
    out = [INDEX_HEAD.format(title=plan.title, n=len(R.row_files(plan.dir)))]
    for p in R.row_files(plan.dir):
        body = p.read_text()
        m = R.SEC.match(body.split("\n", 1)[0])
        st = R.declared_outcome(status_line(body) or "") or "?"
        title = (m.group(2).strip() if m else "").replace("|", "\\|")
        out.append(f"| [{p.stem}]({p.name}) | {st} | {title} |\n")
    return "".join(out)


def report(plan, faults):
    print(f"  {plan.src}: {len(faults)} FAULT(S) — refusing to split")
    for rid, why in faults[:40]:
        print(f"    {rid}: {why}")
    return 1


LINK = re.compile(r"(?:[\w./-]*/)?silent-class-inventory(-2)?\.md#([dD][\w-]+)")
SKIP_DIRS = {".git", "node_modules", "build", "dist", "target", ".venv"}
SKIP_SUFFIX = {".wasm", ".png", ".lock", ".jsonl"}


def do_relink(plans):
    """Rewrite `silent-class-inventory[-2].md#d123` to the row's own file, tree-wide.

    Bare `D1234` mentions in prose are left alone: they are ids, not links. Plain path
    citations with no anchor are left alone too — the pointer file keeps them resolving,
    which is the whole reason the monolith is stubbed rather than deleted."""
    ids = {}
    for i, p in enumerate(plans):
        known = set(p.files) or {q.stem for q in R.row_files(p.dir)}
        for rid in known:
            ids[(i, rid.lower())] = (rid, p.dir)
    changed, unknown = [], []
    for path in sorted(Path(".").rglob("*")):
        if not path.is_file() or path.suffix in SKIP_SUFFIX:
            continue
        if set(path.parts) & SKIP_DIRS or path.parts[0].startswith("."):
            continue
        try:
            text = path.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        if "silent-class-inventory" not in text:
            continue

        def sub(m):
            key = (1 if m.group(1) else 0, m.group(2).lower())
            if key not in ids:
                unknown.append((str(path), m.group(0)))
                return m.group(0)
            rid, d = ids[key]
            return os.path.relpath(d / f"{rid}.md", path.parent)

        new = LINK.sub(sub, text)
        if new != text:
            path.write_text(new)
            changed.append(str(path))
    print(f"  relink: {len(changed)} file(s) rewritten"
          + (f" — {', '.join(changed)}" if changed else ""))
    for where, ref in unknown:
        print(f"    UNKNOWN row in link, left alone: {where}  {ref}")
    return 0


def main(argv):
    mode = {a for a in argv if a.startswith("--")}
    only = None
    if "--only" in argv:
        only = argv[argv.index("--only") + 1]
    bad = mode - {"--verify", "--apply", "--relink", "--only"}
    if bad:
        return die(f"unknown flag(s) {' '.join(sorted(bad))}\n{__doc__}")

    # A spliced row (two status lines, a duplicated id, a status too far from its
    # heading) splits into a bad file; refuse before reading a single row (#2431).
    if mode & {"--verify", "--apply"}:
        scan = subprocess.run([sys.executable, "scripts/inventory/splice-scan.py"],
                              capture_output=True, text=True)
        if scan.returncode != 0:
            return die("splice-scan found a spliced row — fix it before splitting:\n"
                       + scan.stdout + scan.stderr)
    plans = [Plan(s, d) for s, d in SOURCES
             if only is None or only in s or only in d]
    if not plans:
        return die(f"--only {only} matched no inventory")

    rc = 0
    for p in plans:
        n, applied = len(p.rowblocks), p.applied
        print(f"{p.src}  ->  {p.dir}/   {n} rows, "
              f"{sum(1 for b in p.blocks if b.kind == 'prose')} prose block(s)"
              f"{'   [directory already holds rows]' if applied else ''}")
        if not n and applied:
            print(f"  already split: {len(R.row_files(p.dir))} row files on disk")
            continue
        faults = p.check(from_disk=applied and "--apply" not in mode)
        if faults:
            rc |= report(p, faults)
            continue
        print(f"  verify: ids ok · {n} rows verbatim · separators only · rejoin identical")
    if rc:
        return rc
    if "--apply" in mode:
        print("applying:")
        for p in plans:
            rc |= do_apply(p)
    if "--relink" in mode and rc == 0:
        rc |= do_relink(plans)
    if not (mode - {"--only"}):
        print("dry run — pass --verify, --apply and/or --relink")
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
