// Single-sourced golden module set for the self-hosted emitter.
//
// These small `.vl` sources are the BYTE-EXACT golden coverage matrix: each one's
// host-emitted wasm is pinned under `tests/golden/<name>.wasm` and asserted
// byte-for-byte by `tests/selfhost_emit_golden_test.ts`. The self-hosting FIXPOINT
// proof (`tests/selfhost_emit_fixpoint_test.ts`) reuses the EXACT same sources —
// it drives the SELF-EMITTED emitter over them and asserts its output matches the
// very same golden bytes. Keeping the set here means the pin and the fixpoint can
// never drift apart: one source list, two proofs over it.

export type Golden = { name: string; covers: string; src: string };

export const GOLDENS: Golden[] = [
  {
    name: "g_min",
    covers:
      "header + type/func/export/code sections; i32.const; end (the minimal module)",
    src: [
      "function main(): i32 {",
      "  return 42",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_arith",
    covers:
      "binOpcode set (+ - * / %, the 6 compares), call, local.get, if/else/br, recursion (fib)",
    src: [
      "function fib(n: i32): i32 {",
      "  if n < 2 { return n }",
      "  return fib(n - 1) + fib(n - 2)",
      "}",
      "function ops(a: i32, b: i32): i32 {",
      "  let lt = a < b",
      "  let le = a <= b",
      "  let gt = a > b",
      "  let ge = a >= b",
      "  let eq = a == b",
      "  let ne = a != b",
      "  let q = a / b",
      "  let r = a % b",
      "  return lt + le + gt + ge + eq + ne + q + r",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_locals",
    covers:
      "locals vector (i32 runs), reassignment, nested if/else + while (block/loop), fallthrough",
    src: [
      "function count(n: i32): i32 {",
      "  let total = 0",
      "  let i = 0",
      "  while i < n {",
      "    if i == 0 {",
      "      let a = 10",
      "      total = total + a",
      "    } else if i == 1 {",
      "      let b = 20",
      "      total = total + b",
      "    } else {",
      "      let d = 40",
      "      total = total + d",
      "    }",
      "    i = i + 1",
      "  }",
      "  return total",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_struct",
    covers:
      "struct.new/get/set; (ref $i) valtype; rec group with 2 structs; struct param + return",
    src: [
      "type P = { x: i32, y: i32 }",
      "type Q = { a: i32, b: i32 }",
      "function mk(a: i32, b: i32): P {",
      "  return { x: a, y: b }",
      "}",
      "function sumXY(p: P): i32 {",
      "  return p.x + p.y",
      "}",
      "function main(): i32 {",
      "  let p = mk(20, 22)",
      "  let q: Q = { a: 1, b: 2 }",
      "  return sumXY(p) + q.a + q.b",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_union",
    covers:
      "union variant structs + box {tag,value}; ref.cast; is-narrowing; anyref field; union param/return",
    src: [
      "type A = { av: i32 }",
      "type B = { bv: i32 }",
      "type Node = A | B",
      "function f(n: Node): i32 {",
      "  if n is A { return n.av }",
      "  if n is B { return n.bv }",
      "  return 0",
      "}",
      "function mkA(x: i32): Node {",
      "  return { av: x }",
      "}",
      "function main(): i32 {",
      "  return f(mkA(7))",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_multiunion",
    covers:
      "TWO distinct unions coexisting (shared box, globally-unique tags); the type-section stressor",
    src: [
      "type Lit = { val: i32 }",
      "type Var = { vname: string }",
      "type Node = Lit | Var",
      "type TyInt = { width: i32 }",
      "type TyStr = { len: i32 }",
      "type Ty = TyInt | TyStr",
      "function readNode(n: Node): i32 {",
      "  if n is Lit { return n.val }",
      "  return 0",
      "}",
      "function readTy(t: Ty): i32 {",
      "  if t is TyInt { return t.width }",
      "  return 0",
      "}",
      "function main(): i32 {",
      "  let n: Node = { val: 10 }",
      "  let t: Ty = { width: 20 }",
      "  return readNode(n) + readTy(t)",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_i32list",
    covers:
      "raw array + list wrapper; array.new_default; grow path; index/set/.length; push scratch frame",
    src: [
      "function main(): i32 {",
      "  let a: i32[] = []",
      "  let i = 0",
      "  while i < 10 {",
      "    a.push(i)",
      "    i = i + 1",
      "  }",
      "  a[0] = 99",
      "  let sum = 0",
      "  let j = 0",
      "  while j < a.length {",
      "    sum = sum + a[j]",
      "    j = j + 1",
      "  }",
      "  return sum",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_reflist",
    covers:
      "ref backing (nullable elem) + ref-list wrapper; ref-push scratch frame; element field read",
    src: [
      "type Tok = { kind: string, pos: i32 }",
      "type Diag = { msg: string, at: i32 }",
      "type Parser = { toks: Tok[], diags: Diag[], pos: i32 }",
      "let P: Parser = { toks: [], diags: [], pos: 0 }",
      "function f(): i32 {",
      "  P.toks.push({ kind: \"A\", pos: 10 })",
      "  P.diags.push({ msg: \"x\", at: 20 })",
      "  return P.toks[0].pos + P.diags[0].at",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_string",
    covers:
      "string array rep; concat (+); value-eq (==); slice; str-op scratch frame (7 slots); clamp/index",
    src: [
      "function main(): i32 {",
      '  let a = "ab"',
      '  let b = "cde"',
      "  let c = a + b",
      '  let sl = "hello".slice(1, 3)',
      "  let acc = c.length + sl.length",
      '  if sl == "el" { acc = acc + 1 }',
      '  if a == b { acc = acc + 100 }',
      "  acc = acc + c[0]",
      "  return acc",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_strlist",
    covers:
      "string backing + string-list wrapper; str-push scratch frame; string[] field + .push",
    src: [
      "type Box = { names: string[] }",
      "function main(): i32 {",
      "  let b: Box = { names: [] }",
      '  b.names.push("x")',
      '  b.names.push("y")',
      "  let n = b.names.length",
      '  if b.names[1] == "y" { n = n + 0 } else { n = 0 }',
      "  return n",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_map",
    covers:
      "map struct (5 fields); hash/probe/rehash/resize; set/get/has; map scratch frame (12 slots)",
    src: [
      "function main(): i32 {",
      "  let m: {[string]: i32} = Map()",
      '  m["x"] = 7',
      '  m["y"] = 9',
      "  let acc = 0",
      '  if m.has("x") { acc = acc + (m["x"] ?? -1) }',
      '  acc = acc + (m["y"] ?? -1)',
      '  acc = acc + (m["missing"] ?? 100)',
      "  return acc",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_maparray",
    covers:
      "array-of-maps ({[string]:i32}[]): map struct as ref-list elem + map+list scratch frames combined",
    src: [
      "function main(): i32 {",
      "  let scopes: {[string]: i32}[] = []",
      "  scopes.push(Map())",
      "  scopes.push(Map())",
      '  scopes[0]["x"] = 7',
      '  scopes[1]["k"] = 9',
      "  let top = scopes.pop()",
      '  let v = top["k"] ?? -1',
      '  return v + (scopes[0]["x"] ?? -1) + scopes.length',
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_globals",
    covers:
      "global section: module-level let (i32 + struct init); global.get/set; struct.new in init",
    src: [
      "type Counter = { n: i32 }",
      "let base: i32 = 40",
      "let C: Counter = { n: 0 }",
      "function bump(): i32 {",
      "  C.n = C.n + 1",
      "  return C.n",
      "}",
      "function main(): i32 {",
      "  bump()",
      "  bump()",
      "  return base + C.n",
      "}",
      "",
    ].join("\n"),
  },
  {
    name: "g_kitchen",
    covers:
      "cross-section: struct + i32-list + string in one program; full type-section rec-group ordering",
    src: [
      "type Rec = { id: i32, name: string }",
      "function main(): i32 {",
      '  let r: Rec = { id: 5, name: "hi" }',
      "  let xs: i32[] = []",
      "  xs.push(r.id)",
      "  xs.push(r.name.length)",
      '  let s = "a" + "b"',
      "  let sum = 0",
      "  let i = 0",
      "  while i < xs.length {",
      "    sum = sum + xs[i]",
      "    i = i + 1",
      "  }",
      "  return sum + s.length",
      "}",
      "",
    ].join("\n"),
  },
];
