// GENERATED by `deno task gen-std` from `std/*.vl` — do not edit.
// Freshness is gated by tests/std_embedded_test.ts; regenerate after any
// std source change. See docs/std-design.md D3 for who consumes this map
// (the LSP checkers via `withStd`, the playground) and who does NOT (the
// CLI and the Rust host read the `std/` dir directly).

/** Module key (`std:NAME`) → that std module's source. */
export const STD_SOURCES: Record<string, string> = {
  "std:seed": "// `std:seed` — a trivial module whose only job is to prove the `std:`\n// resolution plumbing end to end (both resolvers, the Rust host's std-dir\n// mapping, the CLI's fsRead wrap, the LSP's embedded map). Real std content\n// (`std:fmt`, `std:test`, collections) lands in later slices\n// (docs/std-design.md D4); this file can be retired once any of them exists.\nexport function stdSmoke(): i32 {\n  return 7\n}\n",
};
